---
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install --upgrade pip
  - pip install -r freelancefinder/requirements/development.txt
  - pip install -r freelancefinder/requirements/travis.txt
  - sudo mkdir /var/log/django && sudo chmod 777 /var/log/django
before_script:
  - echo -e "DEBUG=True\nSECRET_KEY='abc123'\nDATABASE_URL='sqlite:////tmp/db.sqlite'\nREDIS_CELERY_URL='redis://localhost:6379/0'\nREDDIT_CLIENT_ID='steve'\nREDDIT_CLIENT_SECRET='steve2'\n" > freelancefinder/.env
script:
  - py.test
  
  # Fail on outdated requirements
  - reqs=$(mktemp)
  - pip list --outdated --format=columns | tee ${reqs}
  - >
    NUM=`wc -l ${reqs} | cut -f1 -d" "`; 
    [ $NUM -eq 0 ] 
    && (echo "Requirements test: pass" && exit 0) 
    || (echo "Requirements test: fail" && exit 1)

  # Fail on code style errors
  - pushd freelancefinder
  - pycodestyle
  - popd

  # Fail on doc style errors
  - pushd freelancefinder
  - pydocstyle --match-dir='(?!migrations).*'
  - popd

  # Fail on pylint errors
  - pushd freelancefinder
  - PYLINTFILES=`find . | grep "py$" | grep -v "lib\|public" | cut -f2 -d"/" | uniq | xargs`
    # Pylint <2.0 doesn't support python 3.6
    # - pylint ${PYLINTFILES}
  - if [ "${TRAVIS_PYTHON_VERSION}" != "3.6" ]; then pylint ${PYLINTFILES}; fi
  - popd
  
after_success:
  - if [ "${TRAVIS_PYTHON_VERSION}" = "3.5" ]; then coveralls; fi
