---
language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - pip install -r freelancefinder/requirements/development.txt
before_script:
  - echo -e "DEBUG=True\nSECRET_KEY='abc123'\nDATABASE_URL='sqlite:////tmp/db.sqlite'\n" > freelancefinder/.env
script:
  - py.test
  
  # Fail on outdated requirements
  - reqs=$(mktemp)
  - pip list --outdated --format=columns | tee ${reqs}
  - >
    NUM=`wc -l ${reqs} | cut -f1 -d" "`; 
    [ $NUM -eq 0 ] 
    && (echo "Requirements test: pass" && exit 0) 
    || (echo "Requirements test: fail" && exit 1)

  # Fail on code style errors
  - pushd freelancefinder
  - pycodestyle
  - popd

  # Fail on doc style errors
  - pushd freelancefinder
  - pydocstyle --match-dir='(?!migrations).*'
  - popd

  # Fail on pylint errors
  - pushd freelancefinder
  - PYLINTFILES=`find . | grep "py$" | grep -v "lib\|public" | cut -f2 -d"/" | uniq | xargs`
  - pylint ${PYLINTFILES}
  - popd
  
after_success:
  - if [ "${TRAVIS_PYTHON_VERSION}" = "3.5" ]; then coveralls; fi
