# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('users', '0004_auto_20170423_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='refresh_frequency',
            field=models.CharField(choices=[('daily', 'daily'), ('twice_a_day', 'twice_a_day'), ('hourly', 'hourly')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
