# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
    ]
