# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 23:27
from __future__ import unicode_literals

from django.db import migrations

NEW_SOURCES = [
    {'code': 'reddit', 'name': 'Reddit', 'url': 'http://www.reddit.com/'},
    {'code': 'hackernews', 'name': 'HackerNews', 'url': 'https://news.ycombinator.com/'},
    {'code': 'fossjobs', 'name': 'FossJobs', 'url': 'https://www.fossjobs.net/'},
]


def load_initial_sources(apps, schema_editor):
    '''Load new source data.'''
    Source = apps.get_model('remotes', 'Source')
    for source in NEW_SOURCES:
        new_source = Source(**source)
        new_source.save()


def delete_all_sources(apps, schema_editor):
    '''Delete all source data.'''
    Source = apps.get_model('remotes', 'Source')
    Source.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_sources, reverse_code=delete_all_sources),
    ]
