# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
