# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:04
from __future__ import unicode_literals

from django.db import migrations

NEW_SOURCE_DATA = {
    'reddit': {'subreddits': ['freelance_forhire', 'forhire', 'python', 'django']},
}


def load_config_data(apps, schema_editor):
    '''Load config data for sources.'''
    Source = apps.get_model('remotes', 'Source')
    for source_code, data in NEW_SOURCE_DATA.items():
        source = Source.objects.filter(code=source_code).first()
        source.config = data
        source.save()


def delete_config_data(apps, schema_editor):
    '''Delete data in the config field.'''
    Source = apps.get_model('remotes', 'Source')
    Source.objects.all().update(config=None)


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0003_source_config'),
    ]

    operations = [
        migrations.RunPython(load_config_data, reverse_code=delete_config_data),
    ]
