---
- name: restart nginx
  #service: name=nginx state=restarted
  supervisorctl: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  #service: name=nginx state=reloaded
  command: nginx -s reload -c /etc/nginx/nginx.conf
