# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0002_initial_data'),
        ('jobs', '0002_auto_20170221_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='post',
            name='unique',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('source', 'unique')]),
        ),
    ]
