# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_post_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_freelance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_job_posting',
            field=models.BooleanField(default=False),
        ),
    ]
