# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('jobs', '0008_job_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=255)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taggit.Tag')),
            ],
        ),
    ]
