# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 17:39
from __future__ import unicode_literals

from django.db import migrations

TAGS = {
    'Full Time': ['full-time', 'fulltime'],
    'Part Time': ['part-time', 'parttime'],
    'Contract': [],
    'Django': [],
    'Python': [],
    'Node.js': ['node'],
    'Javascript': ['js'],
    'Ruby': [],
    'Rails': [],
    'WordPress': [],
    'MongoDB': ['mongo'],
    'PostgreSQL': [],
    'MySQL': [],
    'GoLang': [],
    'Ansible': [],
    'PHP': [],
    'Project Manager': [],
    'Product Manager': [],
    'DevOps': [],
}


def load_tags(apps, schema_editor):
    """Load new tags."""
    from taggit.models import Tag
    from jobs.models import TagVariant
    for tag in TAGS:
        new_tag, created = Tag.objects.get_or_create(name=tag)
        for variant in TAGS[tag]:
            new_variant = TagVariant.objects.get_or_create(variant=variant, tag=new_tag)


def delete_tags(apps, schema_editor):
    """Remove all tags and variants."""
    Tag = apps.get_model('taggit', 'Tag')
    TagVariant = apps.get_model('jobs', 'TagVariant')

    TagVariant.objects.all().delete()
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_tagvariant'),
    ]

    operations = [
        migrations.RunPython(load_tags, reverse_code=delete_tags),
    ]
