# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:35
from __future__ import unicode_literals

from django.db import migrations


def add_fingerprints(apps, schema_editor):
    """Add fingerprints to Jobs and Freelancers."""
    from utils.text import generate_fingerprint

    Jobs = apps.get_model('jobs', 'Job')
    for job in Jobs.objects.filter(fingerprint__isnull=True):
        job.fingerprint = generate_fingerprint(job.description)
        job.save()

    Freelancer = apps.get_model('jobs', 'Freelancer')
    for freelancer in Freelancer.objects.filter(fingerprint__isnull=True):
        freelancer.fingerprint = generate_fingerprint(freelancer.description)
        freelancer.save()


def delete_fingerprints(apps, schema_editor):
    Jobs = apps.get_model('jobs', 'Job')
    Jobs.objects.all().update(fingerprint=None)

    Freelancer = apps.get_model('jobs', 'Freelancer')
    Freelancer.objects.all().update(fingerprint=None)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20170329_1835'),
    ]

    operations = [
        migrations.RunPython(add_fingerprints, reverse_code=delete_fingerprints),
    ]
