# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20170329_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='garbage',
            field=models.BooleanField(default=False),
        ),
    ]
