# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_post_garbage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_freelancer',
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
    ]
