# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20170423_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_job_posting',
        ),
    ]
