# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 14:04
from __future__ import unicode_literals

from django.db import migrations

TAGS = {
    'Clojure': [],
    'Elixir': [],
    'Intern': ['internship', 'unpaid'],
}


def load_tags(apps, schema_editor):
    """Load new tags."""
    from taggit.models import Tag
    from jobs.models import TagVariant
    for tag in TAGS:
        new_tag, created = Tag.objects.get_or_create(name=tag)
        for variant in TAGS[tag]:
            TagVariant.objects.get_or_create(variant=variant, tag=new_tag)


def delete_tags(apps, schema_editor):
    """Remove all tags and variants."""
    Tag = apps.get_model('taggit', 'Tag')
    TagVariant = apps.get_model('jobs', 'TagVariant')

    for tag in TAGS:
        for variant in TAGS[tag]:
            TagVariant.objects.filter(variant=variant).delete()
        Tag.objects.filter(name=tag).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_userjob'),
    ]

    operations = [
        migrations.RunPython(load_tags, reverse_code=delete_tags),
    ]
