---
galaxy_info:
  author: Paul Moss
  description: An Ansible role for installing my dev environment.
  company: Paul Moss
  license: Apache
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
  versions:
    - trusty
    - xenial
  categories:
    - system
dependencies: []
