# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 21:37
from __future__ import unicode_literals

from django.db import migrations

PRIVACY_POLICY_TEXT = """
<h1 class="major">Privacy Policy</h1>

<p>
We don’t sell your personally identifiable information to any third parties.
</p>
<p>
Our site uses Google Analytics to help us understand how visitors engage with the website. We abide by Google policies. They and other third parties may also track you, but we cannot control their policies.
</p>
<p>
The site uses Stripe Checkout for payments.  All of your payment details and billing information are held within the Stripe system and are not available to the owner or operator of Freelance Finder.
</p>
<p>
We use cookies for certain functionality on this website.  You can disable these cookies if you want by following your browser’s directions for disabling cookies.
</p>
<p>
We may send you email to inform you of news of our services or offers. You may unsubscribe by following the instructions that are included in the e-mails that you receive or going to your profile page on this site. If you become a member, we will communicate with you about your account via email.
</p>
<p>
If you have any questions or comments you may contact us at <a href="mailto:info@freelancefinder.work">info@freelancefinder.work</a>.
</p>

<p><small>
Most of this privacy policy is copied from <a href="http://centerforplainlanguage.org/privacy-terms/">the privacy policy for the Center for Plain Language</a>.
</small></p>
"""


def add_privacy_policy(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    Site = apps.get_model('sites', 'Site')
    this_site = Site.objects.filter(domain='freelancefinder.work').first()
    privacy_policy = FlatPage.objects.create(
        url='/about/privacy-policy/',
        title='Privacy Policy',
        content=PRIVACY_POLICY_TEXT,
    )
    privacy_policy.sites.add(this_site)


def delete_privacy_policy(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    FlatPage.objects.filter(url='/about/privacy-policy/').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0006_auto_20170425_0911'),
    ]

    operations = [
        migrations.RunPython(add_privacy_policy, reverse_code=delete_privacy_policy),
    ]
