---
galaxy_info:
  author: Sharp Hall
  description: An Ansible role for installing and configuring gunicorn.
  company: Azavea Inc.
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - precise
  categories:
  - development
