---
- name: Assign Jenkins role
  hosts: all
  become: yes
  become_user: root
  vars:
    jenkins_hostname: 192.168.2.5
    jenkins_admin_username: "admin"
    jenkins_admin_password: "abc123-admin"
  roles:
    - geerlingguy.jenkins
  tasks:
    - name: Turn off security
      lineinfile:
        dest: /var/lib/jenkins/config.xml
        regexp: "<useSecurity>.*"
        line: "<useSecurity>false</useSecurity>"
      notify: restart jenkins

- name: Assign Jenkins role again (to install plugins)
  hosts: all
  become: yes
  become_user: root
  vars:
    jenkins_hostname: 192.168.2.5
    jenkins_admin_username: "admin"
    jenkins_admin_password: "abc123-admin"
    jenkins_plugins_custom:
      - build-name-setter
      - cobertura
      - covcomplplot
      - credentials
      - dependency-check-jenkins-plugin
      - durable-task
      - external-monitor-job
      - git-client
      - git
      - github-api
      - github-branch-source
      - github
      - git-server
      - greenballs
      - handlebars
      - jquery-detached
      - junit
      - plain-credentials
      - scm-api
      - script-security
      - simple-theme-plugin
      - sloccount
      - structs
      - tasks
      - text-finder
      - token-macro
      - translation
      - violations
      - warnings
      - ws-cleanup
  roles:
    - geerlingguy.jenkins
  tasks:
    - name: Install Jenkins plugins using password.
      command: >
        java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
        install-plugin {{ item }}
        creates="{{ jenkins_home }}/plugins/{{ item }}.jpi"
      with_items: "{{ jenkins_plugins_custom }}"
      loop_control:
        pause: 1
      notify: restart jenkins
