---
- name: Install Packages from apt to Control Server
  hosts: all
  become: yes
  become_user: root
  roles:
    - ScorpionResponse.pip
    - ScorpionResponse.django
  vars:
    - use_python3: True
    - django_debug: True
    - django_secret_key: "abc123"
    - django_db_url: "sqlite:////tmp/db.sqlite"
    - django_project_name: "freelancefinder"
    - django_base_dir: /home/ubuntu
    - django_subdirectory: "freelancefinder/"
    - django_git_repo: "https://github.com/ScorpionResponse/freelancefinder.git"
    - django_environment: development
    - django_user_name: ubuntu
    - django_settings:
        REDIS_CELERY_URL: 'redis://localhost:6379/0'
        REDDIT_CLIENT_ID: 'steve'
        REDDIT_CLIENT_SECRET: 'steve4'
  tasks:
    - name: apt-get install packages
      apt: pkg={{ item }} state=installed update_cache=true
      with_items:
        - build-essential
        - git
        - python3
        - python3-pip
        - python3-setuptools
        - python3-venv
        - sqlite3
        - libsqlite3-dev

- name: Prepare control env
  hosts: all
  roles:
    - ScorpionResponse.personal_dev
  tasks:
    - name: Checkout django repo
      git: repo=git@github.com:ScorpionResponse/freelancefinder.git dest=/home/ubuntu/freelancefinder accept_hostkey=True

    - name: Checkout ansible role repos
      git: repo=git@github.com:ScorpionResponse/{{ item }}.git dest=/home/ubuntu/{{ item }} accept_hostkey=True
      with_items:
        - ansible-celery
        - ansible-django
        - ansible-git
        - ansible-gunicorn
        - ansible-nginx
        - ansible-nltk
        - ansible-pip
        - ansible-personal_dev
        - ansible-supervisord

    - name: Update bashrc
      blockinfile:
        dest: /home/ubuntu/.bashrc
        block: |
          alias deploy='pushd ~/freelancefinder/ansible; make webservers; popd'
          alias check='pushd ~/; for i in `ls`; do if [ -d $i/.git ]; then cd $i; RES=`git status -s`; if [ "" != "$RES" ]; then echo "$i - $RES"; fi; cd ../; fi; done; popd'
          source /home/ubuntu/venv/bin/activate

    - name: Install django
      become: yes
      become_user: root
      pip:
        requirements: /home/ubuntu/freelancefinder/freelancefinder/requirements/development.txt
        virtualenv: /home/ubuntu/venv
        virtualenv_python: python3
