---
- name: Install Packages from apt to Control Server
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: apt-get install packages
      apt: pkg={{ item }} state=installed update_cache=true
      with_items:
        - build-essential
        - git
        - python3
        - python3-pip
        - python3-setuptools
        - python3-venv

- name: Prepare control env
  hosts: all
  roles:
    - paul-env
  tasks:
    - name: Checkout django repo
      git: repo=git@github.com:ScorpionResponse/freelancefinder.git dest=/home/ubuntu/freelancefinder accept_hostkey=True

    - name: print SSH_AUTH_SOCK
      debug: msg="SSH_AUTH_SOCK is {{ lookup('env','SSH_AUTH_SOCK') }}"
