---
- name: Configure webserver roles
  hosts: webservers
  become: yes
  become_user: root
  roles:
    - ScorpionResponse.django
    - ScorpionResponse.gunicorn
    - ScorpionResponse.nginx
    - ScorpionResponse.supervisord
