---
- name: Configure webserver roles
  hosts: webservers
  become: yes
  become_user: root
  roles:
    - ScorpionResponse.django
    - ScorpionResponse.gunicorn
    - ScorpionResponse.nginx
    - ScorpionResponse.supervisord
    - geerlingguy.redis
  tasks:
    - name: Restart gunicorn (lazy)
      debug: msg="restart gunicorn"
      changed_when: true
      notify:
        - restart gunicorn
