---
- name: Configure webserver roles
  hosts: webservers
  become: yes
  become_user: root
  roles:
    - ScorpionResponse.celery
    - ScorpionResponse.django
    - ScorpionResponse.gunicorn
    - ScorpionResponse.nginx
    - ScorpionResponse.nltk
    - ScorpionResponse.supervisord
    - geerlingguy.redis
  tasks:
    - name: Restart gunicorn (lazy)
      debug: msg="restart gunicorn"
      changed_when: true
      notify:
        - restart gunicorn

    - name: Restart celeryworker (lazy)
      debug: msg="restart celeryworker"
      changed_when: true
      notify:
        - restart celeryworker

    - name: Restart celerybeat (lazy)
      debug: msg="restart celerybeat"
      changed_when: true
      notify:
        - restart celerybeat
